"""
GEMM + all-reduce using collectives and a producer kernel generated by AnnotationTransformer.
"""

from __future__ import annotations

import importlib
import os
import sys
from pathlib import Path

import torch

from syncopate.communication.code_gen import CommGenerator
from syncopate.communication.comm_runtime.communication_context import CommContext
from syncopate.communication.comm_runtime.operations import CollectiveComm
from syncopate.communication.common_descriptors import build_all_reduce_plan
from syncopate.communication.descriptor import CollectiveOp
from syncopate.computation.transform import AnnotationTransformer
from syncopate.interface.lowering import lower_comm_plan_to_raw_schedules
from tests.test_gemm_rs import configs
from triton_dist.utils import (
    dist_print,
    finalize_distributed,
    group_profile,
    initialize_distributed,
    nvshmem_barrier_all_on_stream,
    perf_func,
    sleep_async,
)


def _load_transformed_gemm_producer():
    transformer = AnnotationTransformer(enable_producer=True)
    example_path = Path("tests/computation/transform/examples/example_persistent_gemm.py")
    transformed_source = transformer.transform(example_path.read_text())
    generated_path = Path("/tmp/" + example_path.name.replace(".py", "_producer_transformed.py"))
    try:
        with open(generated_path, "r") as f:
            existing = f.read()
        if existing != transformed_source:
            with open(generated_path, "w") as f:
                f.write(transformed_source)
    except FileNotFoundError:
        with open(generated_path, "w") as f:
            f.write(transformed_source)

    spec = importlib.util.spec_from_file_location("generated_gemm_producer", generated_path)
    module = importlib.util.module_from_spec(spec)
    sys.modules["generated_gemm_producer"] = module
    spec.loader.exec_module(module)
    return module.gemm


def main():
    gemm_producer = _load_transformed_gemm_producer()

    WORLD_SIZE = int(os.getenv("WORLD_SIZE", "-1"))
    LOCAL_WORLD_SIZE = int(os.getenv("LOCAL_WORLD_SIZE", "-1"))

    TP_GROUP = initialize_distributed()
    rank = TP_GROUP.rank()
    if WORLD_SIZE <= 0:
        WORLD_SIZE = TP_GROUP.size()
    if LOCAL_WORLD_SIZE <= 0:
        LOCAL_WORLD_SIZE = WORLD_SIZE
    torch.cuda.set_device(rank % LOCAL_WORLD_SIZE)

    config = configs["LLaMA-3.1-70B"]
    BM = config["BM"]
    BN = config["BN"]
    BK = config["BK"]
    stage = config["Stage"]

    M = config["M"]
    N = config["N"]
    K = config["K"]
    dtype = torch.float16
    assert K % WORLD_SIZE == 0

    num_comm_sms = 24
    num_splits = 8

    comm_runtime = None

    max_tflops = 0.0
    best_config = (0, 0)

    for num_comm_sms in [8, 16, 24]:
        for num_splits in [2, 4, 8, 16]:
            dist_print(f"num_comm_sms={num_comm_sms}, num_splits={num_splits}")

            K_per_rank = K // WORLD_SIZE
            K_per_rank_pad = (K_per_rank + BK - 1) // BK * BK

            a = torch.randn((M, K_per_rank_pad), device="cuda", dtype=dtype) / 10.0
            b = torch.randn((N, K_per_rank_pad), device="cuda", dtype=dtype) / 10.0
            golden_partial = torch.matmul(a, b.T)
            golden_res = golden_partial.clone()
            torch.distributed.all_reduce(golden_res, group=TP_GROUP)

            device_plans = {
                r: build_all_reduce_plan(
                    shape=(M, N),
                    dtype=dtype,
                    mesh_size=WORLD_SIZE,
                    rank=r,
                    buffer_name="src",
                    num_all_reduces=num_splits,
                    split_axis=0,  # split on axis-0 so each all-reduce chunk is contiguous
                    compute_producer=True,
                )
                for r in range(WORLD_SIZE)
            }

            generator = CommGenerator(device_plans)
            generator.plan_signals()
            lowered = lower_comm_plan_to_raw_schedules(generator)
            schedule = lowered[rank]["src"]

            block_offsets_list = schedule.gen_block_offset_lists()[1:] # FIX: this is a bug when src=dst
            block_shapes_list = schedule.gen_block_shape_lists()[1:]
            signal_offsets_list = schedule.gen_signal_lists()[1:]
            cum_tiles = sum(int(shape[0]) * int(shape[1]) for shape in block_shapes_list)

            block_offsets = torch.tensor(block_offsets_list, device="cuda", dtype=torch.int32)
            block_shapes = torch.tensor(block_shapes_list, device="cuda", dtype=torch.int32)
            signal_offsets = torch.tensor(signal_offsets_list, device="cuda", dtype=torch.int32)

            comm_info = generator.generate_code_for_plan()
            comm_info.local_world_size = comm_info.world_size
            comm_info.num_copy_sms = num_comm_sms
            comm_info.need_green_ctx = True
            # dist_print(f"Rank {rank} CommInfo: {comm_info}", allowed_ranks="all", need_sync=True)

            # sanity check the planner split along axis-0 so collective slices stay contiguous
            for streams in comm_info.operations[rank]:
                for op in streams:
                    if isinstance(op, CollectiveComm) and op.op == CollectiveOp.ALL_REDUCE:
                        assert len(op.src_slice) == 2
                        assert op.src_slice[1].start == 0 and op.src_slice[1].end == N


            if comm_runtime is None:            
                comm_runtime = CommContext(rank, comm_info, multi_info=True)
            else:
                comm_runtime.update_comm_info(comm_info)

            signal_ptr = comm_runtime.compute_signal_bufs[comm_runtime.local_rank]
            counter_ptr = torch.zeros((signal_ptr.numel(),), device="cuda", dtype=torch.int32)

            def fused_gemm_ar_collective():
                comm_runtime.reset_signals()
                counter_ptr.zero_()

                comm_runtime.start_after(torch.cuda.current_stream())

                src_buf = comm_runtime.comm_buffers["src"][comm_runtime.local_rank]
                compute_stream = comm_runtime.compute_stream
                # compute_stream = torch.cuda.current_stream()

                compute_stream.wait_stream(torch.cuda.current_stream())
                with torch.cuda.stream(compute_stream):
                    gemm_producer(
                        a,
                        b,
                        src_buf,
                        WORLD_SIZE,
                        132 - num_comm_sms,
                        BLOCK_SIZE_M=BM,
                        BLOCK_SIZE_N=BN,
                        BLOCK_SIZE_K=BK,
                        GROUP_SIZE_M=8,
                        STAGES=stage,
                        cur_wave_sizes=block_shapes,
                        wave_offsets=block_offsets,
                        signal_offsets=signal_offsets,
                        signal_ptr=signal_ptr,
                        counter_ptr=counter_ptr,
                        cum_tiles=cum_tiles,
                    )

                comm_runtime.execute()
                comm_runtime.end_before(torch.cuda.current_stream())

                return comm_runtime.comm_buffers["src"][comm_runtime.local_rank]

            out = fused_gemm_ar_collective()
            torch.testing.assert_close(out, golden_res, atol=1e-2, rtol=1e-2)
            dist_print(f"Rank {rank} collective ar-gemm results correct", allowed_ranks="all", need_sync=True)

            with group_profile("ar_gemm_collective", False, group=TP_GROUP):
                sleep_async(1000)
                nvshmem_barrier_all_on_stream(torch.cuda.current_stream())
                _, dur_ms = perf_func(fused_gemm_ar_collective, iters=10, warmup_iters=5)

            tflops = 2*M*N*K_per_rank/1e12/(dur_ms/1e3)
            # all reduce the tflops across ranks to get min
            tflops_tensor = torch.tensor(tflops, device="cuda")
            torch.distributed.all_reduce(tflops_tensor, op=torch.distributed.ReduceOp.MIN)
            tflops = tflops_tensor.item()
                
            dist_print(f"tflops: {tflops}, ms: {dur_ms}")

            if tflops > max_tflops:
                max_tflops = tflops
                best_config = (num_comm_sms, num_splits)

            

    dist_print(f"Best tflops: {max_tflops} with num_comm_sms={best_config[0]}, num_splits={best_config[1]}")
    del comm_runtime
    torch.cuda.synchronize()
    torch.distributed.barrier()
    finalize_distributed()


if __name__ == "__main__":
    main()
