"""
Ring all-gather + attention test using kernels generated by AnnotationTransformer.

This mirrors test_allgather_attn_transform.py but exercises the ring-based
all-gather descriptor to verify correctness with dependency-driven scheduling.
"""

from __future__ import annotations

import importlib
import os
import sys
from pathlib import Path

import torch

from syncopate.communication.code_gen import CommGenerator
from syncopate.communication.comm_runtime.communication_context import CommContext
from syncopate.communication.common_descriptors import build_double_ring_all_gather_plan
from syncopate.computation.transform import AnnotationTransformer
from syncopate.interface.lowering import lower_comm_plan_to_raw_schedules
from flash_attn import flash_attn_func
from triton_dist.utils import (
    dist_print,
    finalize_distributed,
    initialize_distributed,
    nvshmem_barrier_all_on_stream,
    perf_func,
    sleep_async,
)


def _load_transformed_attention(example_path: Path):
    transformer = AnnotationTransformer(enable_consumer=True)
    transformed = transformer.transform(example_path.read_text())

    generated_path = Path("/tmp" + example_path.name.replace(".py", "_transformed.py"))
    with open(generated_path, "w") as f:
        f.write(transformed)
    
    spec = importlib.util.spec_from_file_location("generated_tmp_kernel", generated_path)
    module = importlib.util.module_from_spec(spec)
    sys.modules["generated_tmp_kernel"] = module
    spec.loader.exec_module(module)
    
    return module.attention_forward


def _plan_layout_spec(layout: str, B: int, H: int, SEQ: int, DIM: int):
    if layout == "bhsd":
        shape = (2, B, H, SEQ, DIM)
        axes = {"batch": 1, "head": 2, "seq": 3}
    else:
        shape = (2, B, SEQ, H, DIM)
        axes = {"batch": 1, "head": 3, "seq": 2}
    seq_axis = axes["seq"]
    return shape, seq_axis, axes


def _derive_wave_metadata(schedule, seq_per_rank, device, axes):
    block_offsets_src = schedule.gen_block_offset_lists()
    block_shapes_src = schedule.gen_block_shape_lists()
    signal_offsets_src = schedule.gen_signal_lists()
    offsets = []
    shapes = []
    cum_counts = []
    total = 0
    b_idx = axes["batch"]
    h_idx = axes["head"]
    s_idx = axes["seq"]
    for offs, shape in zip(block_offsets_src, block_shapes_src):
        offsets.append([offs[b_idx], offs[h_idx], 0, offs[s_idx]])
        shape_entry = [shape[b_idx], shape[h_idx], seq_per_rank, shape[s_idx]]
        shapes.append(shape_entry)
        total += shape_entry[0] * shape_entry[1] * seq_per_rank
        cum_counts.append(total)
    offsets_t = torch.tensor(offsets, device=device, dtype=torch.int32)
    shapes_t = torch.tensor(shapes, device=device, dtype=torch.int32)
    signal_offsets_t = torch.tensor(signal_offsets_src, device=device, dtype=torch.int32)
    cum_counts_t = torch.tensor(cum_counts, device=device, dtype=torch.int32)
    return offsets_t, shapes_t, signal_offsets_t, cum_counts_t


def _normalize_layout(value: str | None) -> str:
    layout = (value or "bshd").lower()
    if layout not in {"bhsd", "bshd"}:
        raise ValueError(f"Unknown layout {layout}")
    return layout


def _fused_all_gather_attention(attn_fn, q, comm_runtime, wave_kwargs, sm_scale):
    compute_stream = torch.cuda.current_stream()
    comm_buf = comm_runtime.comm_buffers["kv"][comm_runtime.local_rank]
    comm_runtime.reset_signals()
    nvshmem_barrier_all_on_stream(compute_stream)
    comm_runtime.start_after(compute_stream)
    comm_runtime.execute()
    k_plan = comm_buf[0]
    v_plan = comm_buf[1]
    out = attn_fn(q, k_plan, v_plan, sm_scale, **wave_kwargs)
    comm_runtime.end_before(compute_stream)
    return out


def main():
    layout = _normalize_layout(os.getenv("ATTN_LAYOUT"))
    example_file = Path("tests/computation/transform/examples/example_attn.py")
    if layout == "bshd":
        example_file = Path("tests/computation/transform/examples/example_attn_bshd.py")
    attention_fn = _load_transformed_attention(example_file)

    WORLD_SIZE = int(os.getenv("WORLD_SIZE", "1"))
    LOCAL_WORLD_SIZE = int(os.getenv("LOCAL_WORLD_SIZE", "1"))

    TP_GROUP = initialize_distributed()
    rank = TP_GROUP.rank()

    torch.cuda.set_device(rank % LOCAL_WORLD_SIZE)
    dist_print(f"Running ring all-gather layout={layout}")

    B = 1
    H = 32
    SEQ = 4096 * WORLD_SIZE
    DIM = 128
    dtype = torch.float16

    assert SEQ % WORLD_SIZE == 0

    SEQ_per_rank = SEQ // WORLD_SIZE

    BLOCK_Q = 128
    BLOCK_KV = 128
    assert SEQ_per_rank % BLOCK_Q == 0
    assert SEQ % BLOCK_KV == 0

    if layout == "bhsd":
        q = torch.randn((B, H, SEQ_per_rank, DIM), device="cuda", dtype=dtype)
        kv_plan = torch.randn((2, B, H, SEQ_per_rank, DIM), device="cuda", dtype=dtype)
    else:
        q = torch.randn((B, SEQ_per_rank, H, DIM), device="cuda", dtype=dtype)
        kv_plan = torch.randn((2, B, SEQ_per_rank, H, DIM), device="cuda", dtype=dtype)

    plan_shape, plan_seq_axis, layout_axes = _plan_layout_spec(layout, B, H, SEQ, DIM)

    plan_rank = kv_plan.dim()
    seq_axis = layout_axes["seq"]
    perm = [seq_axis] + [dim for dim in range(plan_rank) if dim != seq_axis]
    kv_perm = kv_plan.permute(*perm).contiguous()
    comm_shape = (SEQ,) + tuple(kv_perm.shape[1:])
    comm_res = torch.empty(comm_shape, device="cuda", dtype=dtype)
    torch.distributed.all_gather_into_tensor(comm_res, kv_perm)
    inv_perm = [perm.index(i) for i in range(plan_rank)]
    kv_full_golden_plan = comm_res.permute(*inv_perm).contiguous()

    def _to_flash_order(tensor):
        return tensor.permute(0, 2, 1, 3).contiguous() if layout == "bhsd" else tensor.contiguous()

    def _from_flash_order(tensor):
        return tensor.permute(0, 2, 1, 3).contiguous() if layout == "bhsd" else tensor.contiguous()

    attn_q_flash = _to_flash_order(q)
    k_flash = _to_flash_order(kv_full_golden_plan[0])
    v_flash = _to_flash_order(kv_full_golden_plan[1])
    attn_out_golden = flash_attn_func(attn_q_flash, k_flash, v_flash, softmax_scale=1.0)
    attn_out_golden = _from_flash_order(attn_out_golden)

    device_plans = {
        rank: build_double_ring_all_gather_plan(
            shape=plan_shape,
            dtype=dtype,
            axis=plan_seq_axis,
            mesh_size=WORLD_SIZE,
            inner_mesh_size=2,
            rank=rank,
            buffer_name="kv",
        )
        for rank in range(WORLD_SIZE)
    }

    generator = CommGenerator(device_plans)
    generator.plan_signals()
    schedule = lower_comm_plan_to_raw_schedules(generator)[rank]["kv"]

    block_offsets, block_shapes, signal_offsets, cum_counts = _derive_wave_metadata(
        schedule, SEQ_per_rank, device="cuda", axes=layout_axes
    )
    
    comm_info = generator.generate_code_for_plan()
    comm_info.local_world_size = comm_info.world_size
    comm_runtime = CommContext(rank, comm_info)
    comm_buf = comm_runtime.comm_buffers["kv"][comm_runtime.local_rank]
    comm_buf.zero_()
    seq_start = SEQ_per_rank * rank
    seq_end = SEQ_per_rank * (rank + 1)
    seq_idx = layout_axes["seq"]
    index = [slice(None)] * comm_buf.dim()
    index[seq_idx] = slice(seq_start, seq_end)
    comm_buf[tuple(index)].copy_(kv_plan)

    signal_ptr = comm_runtime.recv_signal_bufs[comm_runtime.local_rank]

    wave_kwargs = {
        "wave_offsets": block_offsets,
        "wave_sizes": block_shapes,
        "cum_wave_sizes": cum_counts,
        "signal_offsets": signal_offsets,
        "signal_ptr": signal_ptr,
        "NUM_WAVES": block_offsets.shape[0],
        "cum_tiles": cum_counts[-1].item(),
    }

    def func():
        return _fused_all_gather_attention(attention_fn, q, comm_runtime, wave_kwargs, 1.0)

    out_triton = func()
    
    torch.testing.assert_close(comm_buf, kv_full_golden_plan, atol=1e-2, rtol=1e-2)
    dist_print(
        f"Rank {rank} ring all_gather results correct for layout={layout}",
    )

    torch.testing.assert_close(out_triton, attn_out_golden, atol=1e-2, rtol=1e-2)
    dist_print(
        f"Rank {rank} ring attention results correct for layout={layout}",
    )

    sleep_async(1000)
    _, dur_ms = perf_func(func, iters=10, warmup_iters=5)

    flops_per_matmul = 2.0 * B * H * SEQ * SEQ * DIM
    total_flops = 2 * flops_per_matmul
    per_gpu_flops = total_flops / WORLD_SIZE
    tflops = per_gpu_flops / 1e12 / (dur_ms / 1e3)
    dist_print(
        f"layout={layout} ring tflops: {tflops} time: {dur_ms}, total_flops: {total_flops}",
        allowed_ranks="all",
        need_sync=True,
    )

    del comm_runtime

    finalize_distributed()


if __name__ == "__main__":
    main()
