"""
GEMM + reduce-scatter test using kernels generated by AnnotationTransformer (producer path).
"""

from __future__ import annotations

import importlib
import os
import sys
from pathlib import Path

import torch

from syncopate.communication.code_gen import CodeGenOptions, CommGenerator
from syncopate.communication.comm_runtime.communication_context import CommContext
from syncopate.communication.common_descriptors import build_all_to_all_plan
from syncopate.computation.transform import AnnotationTransformer
from syncopate.interface.lowering import lower_comm_plan_to_raw_schedules
from tests.test_gemm_rs import ring_reduce_tma, configs
from triton_dist.kernels.nvidia.common_ops import _wait_eq_cuda
from triton_dist.utils import (
    dist_print,
    finalize_distributed,
    initialize_distributed,
    nvshmem_barrier_all_on_stream,
    perf_func,
    sleep_async,
)


def _load_transformed_gemm_producer():
    transformer = AnnotationTransformer(enable_producer=True)
    example_path = Path("tests/computation/transform/examples/example_persistent_gemm.py")
    transformed_source = transformer.transform(example_path.read_text())
    generated_path = Path("/tmp/" + example_path.name.replace(".py", "_producer_transformed.py"))
    try:
        with open(generated_path, "r") as f:
            existing = f.read()
        if existing != transformed_source:
            with open(generated_path, "w") as f:
                f.write(transformed_source)
    except FileNotFoundError:
        with open(generated_path, "w") as f:
            f.write(transformed_source)

    spec = importlib.util.spec_from_file_location("generated_gemm_producer", generated_path)
    module = importlib.util.module_from_spec(spec)
    sys.modules["generated_gemm_producer"] = module
    spec.loader.exec_module(module)
    return module.gemm


def main():
    gemm_producer = _load_transformed_gemm_producer()

    WORLD_SIZE = int(os.getenv("WORLD_SIZE", "-1"))
    LOCAL_WORLD_SIZE = int(os.getenv("LOCAL_WORLD_SIZE", "-1"))

    TP_GROUP = initialize_distributed()
    rank = TP_GROUP.rank()
    if WORLD_SIZE <= 0:
        WORLD_SIZE = TP_GROUP.size()
    if LOCAL_WORLD_SIZE <= 0:
        LOCAL_WORLD_SIZE = WORLD_SIZE
    torch.cuda.set_device(rank % LOCAL_WORLD_SIZE)

    config = configs["LLaMA-3.1-405B"]
    use_tma = False

    BM=128
    BN=256
    BK=64
    stage=3

    M = config["M"]
    N = config["N"]
    K = config["K"]
    dtype = torch.float16
    assert K % WORLD_SIZE == 0

    K_per_rank = K // WORLD_SIZE
    K_per_rank_pad = (K_per_rank + BK - 1) // BK * BK

    # generate data
    a = torch.randn((M, K_per_rank_pad), device="cuda", dtype=dtype) / 10.0
    b = torch.randn((N, K_per_rank_pad), device="cuda", dtype=dtype) / 10.0
    c = torch.empty((M // WORLD_SIZE, N), dtype=dtype, device="cuda")

    golden_c_partial = torch.matmul(a, b.T)
    golden_res = torch.empty((M // WORLD_SIZE, N), dtype=a.dtype, device=a.device)
    torch.distributed.reduce_scatter_tensor(golden_res, golden_c_partial, group=TP_GROUP)

    device_plans = {
        r: build_all_to_all_plan(
            shape=(M, N),
            dtype=dtype,
            mesh_size=WORLD_SIZE,
            rank=r,
            src_buffer="src",
            dst_buffer="dst",
            transfer_kind="push",
            compute_producer=True,
        )
        for r in range(WORLD_SIZE)
    }

    generator = CommGenerator(device_plans)
    generator.plan_signals()
    schedule = lower_comm_plan_to_raw_schedules(generator)[rank]["src"]
    options = CodeGenOptions(use_tma=use_tma, copy_engine=False)
    comm_info = generator.generate_code_for_plan(options)
    comm_info.local_world_size = comm_info.world_size
    dist_print(f"Rank {rank} CommInfo: {comm_info}", allowed_ranks="all", need_sync=True)

    block_offsets_list = schedule.gen_block_offset_lists()
    block_shapes_list = schedule.gen_block_shape_lists()
    signal_offsets_list = schedule.gen_signal_lists()

    block_offsets = torch.tensor(block_offsets_list, device="cuda", dtype=torch.int32)
    block_shapes = torch.tensor(block_shapes_list, device="cuda", dtype=torch.int32)
    signal_offsets = torch.tensor(signal_offsets_list, device="cuda", dtype=torch.int32)

    cum_tiles = sum(int(shape[0]) * int(shape[1]) for shape in block_shapes_list)

    dist_print(f"Rank {rank} block_offsets: {block_offsets_list}", allowed_ranks="all", need_sync=True)
    dist_print(f"Rank {rank} block_shapes: {block_shapes_list}", allowed_ranks="all", need_sync=True)
    dist_print(f"Rank {rank} signal_offsets: {signal_offsets_list}", allowed_ranks="all", need_sync=True)

    comm_runtime = CommContext(rank, comm_info)
    comm_stream = torch.cuda.Stream()

    signal_ptr = comm_runtime.compute_signal_bufs[comm_runtime.local_rank]
    counter_ptr = torch.zeros((signal_ptr.numel(),), device="cuda", dtype=torch.int32)

    def fused_gemm_rs():
        comm_runtime.reset_signals()
        counter_ptr.zero_()

        barrier_reset = torch.cuda.Event()
        barrier_reset.record(torch.cuda.current_stream())

        src_buf = comm_runtime.comm_buffers["src"][comm_runtime.local_rank]
        gemm_producer(
            a,
            b,
            src_buf,
            WORLD_SIZE,
            132 - comm_runtime.info.num_copy_sms,
            BLOCK_SIZE_M=BM,
            BLOCK_SIZE_N=BN,
            BLOCK_SIZE_K=BK,
            GROUP_SIZE_M=8,
            STAGES=stage,
            cur_wave_sizes=block_shapes,
            wave_offsets=block_offsets,
            signal_offsets=signal_offsets,
            signal_ptr=signal_ptr,
            counter_ptr=counter_ptr,
            cum_tiles=cum_tiles,
        )

        comm_stream.wait_event(barrier_reset)
        nvshmem_barrier_all_on_stream(comm_stream)
        comm_runtime.start_after(comm_stream)
        comm_runtime.execute(neglect_local=True)
        comm_runtime.end_before(comm_stream)

        recv_done_signals = comm_runtime.recv_signal_bufs[comm_runtime.local_rank]

        for offset in range(recv_done_signals.shape[0]):
            _wait_eq_cuda(recv_done_signals[offset], 1, torch.cuda.current_stream())

        dst_buf = comm_runtime.comm_buffers["dst"][comm_runtime.local_rank]
        ring_reduce_tma(dst_buf, c, src_buf, rank)

    comm_runtime.info.num_copy_sms = 8
    fused_gemm_rs()
    torch.testing.assert_close(c, golden_res, atol=1e-2, rtol=1e-2)
    dist_print(f"Rank {rank} rs-gemm transform results correct", allowed_ranks="all", need_sync=True)

    for comm_sms in [4, 6, 8, 12, 16, 20]:
        comm_runtime.info.num_copy_sms = comm_sms
        sleep_async(1000)
        _, dur_ms = perf_func(fused_gemm_rs, iters=10, warmup_iters=5)
        dist_print(f"num_comm_sms: {comm_runtime.info.num_copy_sms}")
        dist_print(f"tflops: {2*M*N*K_per_rank/1e12/(dur_ms/1e3)}, ms: {dur_ms}", allowed_ranks="all", need_sync=True)

    del comm_runtime
    torch.cuda.synchronize()
    torch.distributed.barrier()
    finalize_distributed()


if __name__ == "__main__":
    main()
