

from dataclasses import dataclass
from typing import List, Literal, Optional, Tuple
import abc

from syncopate.communication.descriptor import ReduceOp, Signal


TileRole = Literal["producer", "consumer"]


# Information about a single block in the schedule
@dataclass
class TileCoord:
    """Describes the origin and extent of a tile within an N-D tensor."""

    offsets: Tuple[int, ...]
    shape: Tuple[int, ...]

    def __post_init__(self) -> None:
        if len(self.offsets) != len(self.shape):
            raise ValueError("offsets and shape must have identical length")
        if any(dim < 0 for dim in self.offsets):
            raise ValueError("offsets must be non-negative")
        if any(size <= 0 for size in self.shape):
            raise ValueError("shape must contain strictly positive sizes")

    @property
    def ndim(self) -> int:
        return len(self.offsets)

    def as_ranges(self) -> Tuple[Tuple[int, int], ...]:
        return tuple((start, start + size) for start, size in zip(self.offsets, self.shape))
    
    def __repr__(self) -> str:
        return f"TileCoord(offsets={self.offsets}, shape={self.shape})"


@dataclass
class TileBlock:
    """Tile plus the signals that publish its readiness."""

    tile: TileCoord
    signal: Optional[Signal] = None
    # Which remote rank the tile is exchanged with for direct intra-kernel
    # communication. None when the block is purely local (data already resident
    # on the device, no peer interaction).
    peer_rank: Optional[int] = None
    # If the corresponding transfer is a reduce-style op, this records the
    # reduction operator. Used to infer that fused producers should use
    # atomic_add instead of plain stores.
    reduce_op: Optional[ReduceOp] = None
    # Whether the compute kernel acts as the producer (writes the tile) or the
    # consumer (reads the tile) of this block when fused.
    role: Optional[TileRole] = None
    # Offsets within the peer's allocation that this tile maps to. For PUSH
    # transfers this is the dst_region's offsets on the peer; for PULL it's the
    # src_region's offsets on the peer. None when there is no remote
    # counterpart (purely local block).
    dst_offsets: Optional[Tuple[int, ...]] = None


# The raw schedule generated by the communication planner, flexible but complex
@dataclass
class RawSchedule:
    num_waves: int
    block_infos: List[List[TileBlock]]
    global_shape: Tuple[int, ...]

    def __post_init__(self) -> None:
        if self.num_waves <= 0:
            raise ValueError("num_waves must be positive")
        if len(self.block_infos) != self.num_waves:
            raise ValueError("block_infos length must match num_waves")
        if any(len(wave) == 0 for wave in self.block_infos):
            raise ValueError("each wave must contain at least one block")
        if any(
            block.tile.ndim != len(self.global_shape)
            for wave in self.block_infos
            for block in wave
        ):
            raise ValueError("all blocks must have the same number of dimensions as global_shape")

    def __repr__(self) -> str:
        return (f"RawSchedule(num_waves={self.num_waves}, "
                f"global_shape={self.global_shape}, "
                f"block_infos=[{self.block_infos}])")
        
    def gen_block_offset_lists(self) -> List[List[int]]:
        """Generate lists of block offsets for each wave."""
        offset_lists = []
        for wave in self.block_infos:
            for block in wave:
                offset_lists.append(list(block.tile.offsets))
        return offset_lists
    
    def gen_block_shape_lists(self) -> List[List[int]]:
        """Generate lists of block shapes for each wave."""
        shape_lists = []
        for wave in self.block_infos:
            for block in wave:
                shape_lists.append(list(block.tile.shape))
        return shape_lists
    
    def gen_signal_lists(self) -> List[int]:
        """genrate signal offsets for each block"""
        signal_lists = []
        for wave in self.block_infos:
            for block in wave:
                if block.signal is None:
                    signal_lists.append(-1)
                else:
                    signal_lists.append(block.signal.dst_offset)
        return signal_lists

    def gen_target_rank_list(self) -> List[int]:
        """Per-block peer rank used for intra-kernel direct-write/read fusion.

        Falls back to -1 for purely local blocks. Callers should validate that
        the schedule actually carries peer information before using the list.
        """
        ranks: List[int] = []
        for wave in self.block_infos:
            for block in wave:
                ranks.append(-1 if block.peer_rank is None else block.peer_rank)
        return ranks

    def gen_dst_offset_lists(self) -> List[List[int]]:
        """Per-block peer-side offsets where this tile lands in the peer's
        allocation.

        For blocks without a remote counterpart (None ``dst_offsets``) we fall
        back to the tile's own offsets — that keeps the canonical local-GEMM
        code path correct because the rewrite then adds back exactly what was
        subtracted, leaving the access at its original global location.
        """
        result: List[List[int]] = []
        for wave in self.block_infos:
            for block in wave:
                if block.dst_offsets is not None:
                    result.append(list(block.dst_offsets))
                else:
                    result.append(list(block.tile.offsets))
        return result

    def is_reduce(self) -> bool:
        """True if any block in this schedule originates from a reduce transfer."""
        for wave in self.block_infos:
            for block in wave:
                if block.reduce_op is not None:
                    return True
        return False

    def role(self) -> Optional[TileRole]:
        """Aggregate role across blocks; raises if blocks disagree.

        Returns None when no block carries a role (purely local schedule).
        """
        seen: Optional[TileRole] = None
        for wave in self.block_infos:
            for block in wave:
                if block.role is None:
                    continue
                if seen is None:
                    seen = block.role
                elif seen != block.role:
                    raise ValueError(
                        f"schedule blocks disagree on role: {seen!r} vs {block.role!r}"
                    )
        return seen

# try to use a simpler function to describe the schedule
# fallback to RawSchedule if not possible
# this enable to use a simpler schedule in most cases
# can be used to generate math formulas for triton kernels to avoid reading a schedule from memory
@dataclass
class SimplifiedSchedule:
    origin_schedule: RawSchedule
    simplified_schedule: "None | SimpleSchedule" = None

    def simplify(self) -> bool:
        # try to simplify the schedule
        simple_schedules = [subclass for subclass in SimpleSchedule.__subclasses__()]
        simple_schedules = sorted(simple_schedules, key=lambda x: x.priority)

        # try each simple schedule in order of priority
        for schedule_cls in simple_schedules:
            try:
                self.simplified_schedule = schedule_cls(self.origin_schedule)
                print(f"Simplified schedule to {schedule_cls.__name__}")
                return True
            except Exception as e:
                print(f"Failed to simplify schedule to {schedule_cls.__name__}: {e}")
                continue

        return False
        

class SimpleSchedule(abc.ABC):
    priority = 99

    @abc.abstractmethod
    def __init__(self, raw_schedule: RawSchedule):
        pass

    @abc.abstractmethod
    def __repr__(self) -> str:
        pass


# resulting schedule from ring-stiled communication or swizzled direct schedule
# should cover most use cases
class Mod1DSchedule(SimpleSchedule):
    priority = 1 # very simple schedule, highest priority

    num_waves: int
    global_shape: Tuple[int, ...]
    stride: int
    starting_offset: int
    schedule_axis: int

    def __init__(self, raw_schedule: RawSchedule):
        # check if the schedule can be represented as a mod-1D schedule
        self.num_waves = raw_schedule.num_waves
        self.global_shape = raw_schedule.global_shape

        # check all waves only have one block
        if any(len(wave) != 1 for wave in raw_schedule.block_infos):
            raise ValueError("all waves must contain exactly one block")
        
        # check all blocks have the same shape
        first_block_shape = raw_schedule.block_infos[0][0].tile.shape
        if any(wave[0].tile.shape != first_block_shape for wave in raw_schedule.block_infos):
            raise ValueError("all blocks must have the same shape")
        
        # find the axis along which the schedule is define
        partial_axes = []
        for axis in range(len(self.global_shape)):
            if first_block_shape[axis] < self.global_shape[axis]:
                partial_axes.append(axis)

        if len(partial_axes) != 1:
            raise ValueError("schedule must be defined along exactly one axis")
        
        self.schedule_axis = partial_axes[0]
        self.stride = first_block_shape[self.schedule_axis]
        self.starting_offset = raw_schedule.block_infos[0][0].tile.offsets[self.schedule_axis]

        # check the offsets of the signals
        for wave_idx, wave in enumerate(raw_schedule.block_infos):
            block = wave[0]
            if wave_idx == 0:
                if block.signal is not None:
                    raise ValueError("first block (local) must not have any signals")
            else:
                expected_offset = wave_idx - 1
                if block.signal is None or block.signal.dst_offset != expected_offset:
                    raise ValueError("signal offsets do not match expected pattern")
        

    def __post_init__(self) -> None:
        if self.schedule_axis < 0 or self.schedule_axis >= len(self.global_shape):
            raise ValueError("schedule_axis must be a valid axis index")
        if self.stride * self.num_waves != self.global_shape[self.schedule_axis]:
            raise ValueError("stride * num_waves must equal the size of the schedule_axis in global_shape")

    def __repr__(self) -> str:
        return (f"Mod1DSchedule(num_waves={self.num_waves}, "
                f"global_shape={self.global_shape}, "
                f"stride={self.stride}, "
                f"starting_offset={self.starting_offset}, "
                f"schedule_axis={self.schedule_axis})")