"""All-gather plan builder utilities."""

from __future__ import annotations

from typing import Literal, Sequence

from ..descriptor import BufferRegion, DevicePlan, Transfer, TransferOp, XferDependency
from .utils import row_major_strides
import torch


# Directly define how to do all-gather with 1D swizzle.
# Should also be generated by planning algorithm to be implemented.
def build_all_gather_plan_1d_swizzle(
    shape: Sequence[int],
    dtype: torch.dtype,
    axis: int,
    mesh_size: int,
    rank: int,
    buffer_name: str = "buffer",
    transfer_kind: Literal["push", "pull"] = "pull",
) -> DevicePlan:
    """Build a minimal all-gather plan using only local buffer metadata.

    Args:
        shape: Logical tensor shape visible on the current rank.
        elem_size: Size of each element in bytes.
        axis: Dimension index partitioned across the mesh.
        mesh_size: Number of devices participating in the mesh.
        rank: Current device rank within the mesh.
        buffer_name: Logical name for the shared buffer.
        transfer_kind: Strategy for the runtime (issue pushes or pulls).
    """

    elem_size = dtype.itemsize
    if mesh_size <= 0:
        raise ValueError("mesh_size must be positive")
    if elem_size <= 0:
        raise ValueError("elem_size must be positive")

    shape = tuple(shape)
    ndim = len(shape)
    if ndim == 0:
        raise ValueError("all_gather expects at least one dimension")

    axis = _normalize_dim(axis, ndim)
    axis_len = shape[axis]
    if axis_len % mesh_size:
        raise ValueError(
            f"axis length {axis_len} along dim {axis} must be divisible by mesh_size {mesh_size}"
        )
    chunk = axis_len // mesh_size

    strides = row_major_strides(shape)
    plan = DevicePlan(dev=rank)

    plan.tensors_involved[buffer_name] = (torch.Size(shape), dtype)

    if transfer_kind not in {"push", "pull"}:
        raise ValueError("transfer_kind must be 'push' or 'pull'")

    def shard_region(shard_index: int) -> BufferRegion:
        axis_slices = []
        for dim, dim_len in enumerate(shape):
            if dim == axis:
                start = shard_index * chunk
                axis_slices.append((start, start + chunk))
            else:
                axis_slices.append((0, dim_len))
        return BufferRegion.from_slices(
            elem_size=elem_size,
            strides=strides,
            slices=axis_slices,
        )

    local_region = shard_region(rank)
    plan.local_regions.setdefault(buffer_name, []).append(local_region)

    if transfer_kind == "pull":
        for i in range(mesh_size):
            peer = (i + rank) % mesh_size
            if peer == rank:
                continue  # local shard already in place

            peer_region = shard_region(peer)
            plan.add_op(
                Transfer(
                    op=TransferOp.PULL,
                    dst_buf=buffer_name,
                    dst_region=peer_region,
                    peer=peer,
                    chunk_idx=peer, # all gather does not have replicated data at begining, so chunk_idx is set to peer
                    src_buf=buffer_name,
                    src_region=peer_region,
                )
            )
    else:  # push
        for i in range(mesh_size):
            peer = (i + rank) % mesh_size
            if peer == rank:
                continue

            plan.add_op(
                Transfer(
                    op=TransferOp.PUSH,
                    src_buf=buffer_name,
                    src_region=local_region,
                    peer=peer,
                    chunk_idx=rank, # all gather does not have replicated data at begining, so chunk_idx is set to rank
                    dst_buf=buffer_name,
                    dst_region=local_region,
                )
            )

    return plan


def _normalize_dim(axis: int, ndim: int) -> int:
    if axis < 0:
        axis += ndim
    if not 0 <= axis < ndim:
        raise IndexError(f"axis {axis} out of range for tensor with {ndim} dims")
    return axis


__all__ = ["build_all_gather_plan_1d_swizzle"]


def build_ring_all_gather_plan(
    shape: Sequence[int],
    dtype: torch.dtype,
    axis: int,
    mesh_size: int,
    rank: int,
    buffer_name: str = "buffer",
) -> DevicePlan:
    """Build a ring-based all-gather plan using push operations.

    Each rank only communicates with its neighbors in the ring. Transfers are
    chained with explicit dependencies so that a rank forwards a chunk only
    after it has been received from its upstream peer.
    """

    elem_size = dtype.itemsize
    if mesh_size <= 0:
        raise ValueError("mesh_size must be positive")
    if elem_size <= 0:
        raise ValueError("elem_size must be positive")

    shape = tuple(shape)
    ndim = len(shape)
    if ndim == 0:
        raise ValueError("all_gather expects at least one dimension")

    axis = _normalize_dim(axis, ndim)
    axis_len = shape[axis]
    if axis_len % mesh_size:
        raise ValueError(
            f"axis length {axis_len} along dim {axis} must be divisible by mesh_size {mesh_size}"
        )
    chunk = axis_len // mesh_size
    if chunk == 0:
        raise ValueError("all-gather requires non-empty slices along the gather axis")

    strides = row_major_strides(shape)
    plan = DevicePlan(dev=rank)
    plan.tensors_involved[buffer_name] = (torch.Size(shape), dtype)

    def shard_region(shard_index: int) -> BufferRegion:
        axis_slices = []
        for dim, dim_len in enumerate(shape):
            if dim == axis:
                start = shard_index * chunk
                axis_slices.append((start, start + chunk))
            else:
                axis_slices.append((0, dim_len))
        return BufferRegion.from_slices(
            elem_size=elem_size,
            strides=strides,
            slices=axis_slices,
        )

    local_region = shard_region(rank)
    plan.local_regions.setdefault(buffer_name, []).append(local_region)

    if mesh_size == 1:
        return plan

    next_rank = (rank + 1) % mesh_size
    prev_rank = (rank - 1 + mesh_size) % mesh_size

    for step in range(mesh_size - 1):
        chunk_owner = (rank - step) % mesh_size
        dependency = []
        if step > 0:
            dependency.append(
                XferDependency(
                    depend_rank=prev_rank,
                    depend_xfer_stream=0,
                    depend_xfer_idx=step - 1,
                )
            )

        region = shard_region(chunk_owner)
        plan.add_op(
            Transfer(
                op=TransferOp.PUSH,
                src_buf=buffer_name,
                src_region=region,
                dst_buf=buffer_name,
                dst_region=region,
                chunk_idx=chunk_owner,
                peer=next_rank,
                dependency=dependency,
            )
        )

    return plan


def build_double_ring_all_gather_plan(
    shape: Sequence[int],
    dtype: torch.dtype,
    axis: int,
    mesh_size: int,
    inner_mesh_size: int,
    rank: int,
    buffer_name: str = "buffer",
) -> DevicePlan:
    """Hierarchical (double-ring) all-gather: inner group ring + outer group ring.

    Devices are partitioned into contiguous groups of size ``inner_mesh_size``.
    Each group first performs an intra-group ring all-gather of its local shards.
    """

    elem_size = dtype.itemsize
    if mesh_size <= 0:
        raise ValueError("mesh_size must be positive")
    if inner_mesh_size <= 0:
        raise ValueError("inner_mesh_size must be positive")
    if mesh_size % inner_mesh_size:
        raise ValueError("mesh_size must be divisible by inner_mesh_size")
    if elem_size <= 0:
        raise ValueError("elem_size must be positive")

    shape = tuple(shape)
    ndim = len(shape)
    if ndim == 0:
        raise ValueError("all_gather expects at least one dimension")

    axis = _normalize_dim(axis, ndim)
    axis_len = shape[axis]
    if axis_len % mesh_size:
        raise ValueError(
            f"axis length {axis_len} along dim {axis} must be divisible by mesh_size {mesh_size}"
        )
    chunk = axis_len // mesh_size
    if chunk == 0:
        raise ValueError("all-gather requires non-empty slices along the gather axis")

    group_size = inner_mesh_size
    num_groups = mesh_size // group_size
    group_id = rank // group_size
    inner_rank = rank % group_size

    strides = row_major_strides(shape)
    plan = DevicePlan(dev=rank)
    plan.tensors_involved[buffer_name] = (torch.Size(shape), dtype)

    def shard_region(shard_index: int) -> BufferRegion:
        axis_slices = []
        for dim, dim_len in enumerate(shape):
            if dim == axis:
                start = shard_index * chunk
                axis_slices.append((start, start + chunk))
            else:
                axis_slices.append((0, dim_len))
        return BufferRegion.from_slices(
            elem_size=elem_size,
            strides=strides,
            slices=axis_slices,
        )

    local_region = shard_region(rank)
    plan.local_regions.setdefault(buffer_name, []).append(local_region)

    if mesh_size == 1:
        return plan

    # 1) Nested ring: for each outer group chunk, circulate inside the group, then forward to next group.
    inner_neighbor = group_id * group_size + (inner_rank + 1) % group_size
    prev_inner_peer = group_id * group_size + (inner_rank - 1 + group_size) % group_size
    outer_steps = num_groups
    next_group_id = (group_id + 1) % num_groups
    prev_group_id = (group_id - 1 + num_groups) % num_groups
    next_peer = next_group_id * group_size + inner_rank
    prev_peer = prev_group_id * group_size + inner_rank
    ops_per_outer_step = group_size  # (inner_size - 1) inner pushes + 1 outer push

    for outer_step in range(outer_steps):
        chunk_owner_group = (group_id - outer_step) % num_groups

        # Wait for previous outer hop (except for the first chunk).
        outer_dependency: list[XferDependency] = []
        if outer_step > 0:
            outer_dependency.append(
                XferDependency(
                    depend_rank=prev_peer,
                    depend_xfer_stream=0,
                    depend_xfer_idx=outer_step * ops_per_outer_step - 1,
                )
            )

        # Inner ring across the group to circulate this chunk.
        for inner_step in range(group_size - 1):
            # chunk currently owned by rank within the group
            owner_inner_rank = (inner_rank + outer_step - inner_step) % group_size
            owner_global_rank = chunk_owner_group * group_size + owner_inner_rank
            region = shard_region(owner_global_rank)

            if inner_step == 0:
                dependency = outer_dependency
            else:
                dependency = [
                    XferDependency(
                        depend_rank=prev_inner_peer,
                        depend_xfer_stream=0,
                        depend_xfer_idx=outer_step * ops_per_outer_step + inner_step - 1,
                    )
                ]
            plan.add_op(
                Transfer(
                    op=TransferOp.PUSH,
                    src_buf=buffer_name,
                    src_region=region,
                    dst_buf=buffer_name,
                    dst_region=region,
                    chunk_idx=chunk_owner_group * group_size + inner_rank,
                    peer=inner_neighbor,
                    dependency=dependency,
                )
            )

        # Outer hop to the next group (depends on last inner step if any), skipped on the final outer step.
        if outer_step < outer_steps - 1:
            owner_inner_rank = (inner_rank + outer_step + 1) % group_size
            owner_global_rank = chunk_owner_group * group_size + owner_inner_rank
            region = shard_region(owner_global_rank)
            if group_size == 1:
                outer_dep_for_send: list[XferDependency] = outer_dependency
            else:
                outer_dep_for_send = [
                    XferDependency(
                        depend_rank=prev_inner_peer,
                        depend_xfer_stream=0,
                        depend_xfer_idx=outer_step * ops_per_outer_step + (group_size - 2),
                    )
                ]
            plan.add_op(
                Transfer(
                    op=TransferOp.PUSH,
                    src_buf=buffer_name,
                    src_region=region,
                    dst_buf=buffer_name,
                    dst_region=region,
                    chunk_idx=chunk_owner_group * group_size + inner_rank,
                    peer=next_peer,
                    dependency=outer_dep_for_send,
                )
            )

    return plan


__all__.append("build_ring_all_gather_plan")
__all__.append("build_double_ring_all_gather_plan")
